database:
  path: ./data/database.db
monitors:
- enabled: true
  exclude_patterns:
  - '*.tmp'
  - '*.part'
  - .DS_Store
  obfuscate_enabled: true
  source: /path/to/your/source
  targets:
  - name: 阿里云盘1
    path: /path/to/your/target1
  - name: 115网盘
    path: /path/to/your/target2
  template_files_path: /path/to/templates
notification:
  enabled: true
  serverchan_sendkey: sctp13922twpjwr8sh4gr8bdeupbzjda
  serverchan_url: https://13922.push.ft07.com/send/sctp13922twpjwr8sh4gr8bdeupbzjda.send
server:
  debug: false
  host: 0.0.0.0
  port: 8080
taosync:
  check_interval: 60
  enabled: true
  job_id: 1
  password: a123456!@
  url: http://10.10.10.17:8023
  username: admin
