database:
  mysql:
    charset: utf8mb4
    database: file_link_monitor_v2
    host: 101.35.224.59
    password: e0237e873f08ad0b
    port: 3306
    user: root
  sqlite:
    path: ./data/database.db
  type: mysql
monitors:
- enabled: true
  exclude_patterns:
  - '*.tmp'
  - '*.part'
  - .DS_Store
  obfuscate_enabled: true
  source: /path/to/your/source
  targets:
  - name: 夸克网盘
    path: /media/夸克网盘
  - name: 百度网盘
    path: /media/网盘
  - name: 迅雷网盘
    path: /media/迅雷网盘
  template_files_path: /path/to/templates
notification:
  enabled: true
  serverchan_sendkey: sctp13922twpjwr8sh4gr8bdeupbzjda
  serverchan_url: https://13922.push.ft07.com/send/sctp13922twpjwr8sh4gr8bdeupbzjda.send
openlist:
  path_prefix: /A-闲鱼影视（自动更新）
  token: openlist-1e33e197-915f-4894-adfb-514387a5054dLjiXDkXmIe21Yub5F9g9b6REyJLNVuB2DxV9vc4fnDcKiZwLMbivLsN7y8K7oum4
  url: http://10.10.10.17:5255
pansou:
  cloud_types:
  - baidu
  - quark
  - xunlei
  enabled: true
  token: ''
  url: http://10.10.10.17:9978
server:
  debug: false
  host: 0.0.0.0
  port: 8080
taosync:
  check_interval: 60
  enabled: true
  job_id:
  - 1
  - 2
  password: a123456!@
  url: http://10.10.10.17:8023
  username: admin
wechat:
  agent_id: 1000004
  callback_url: https://link.frp.naspt.vip/api/wechat/callback
  corp_id: wwdf6106d7f613ab4d
  default_user: '@all'
  enabled: true
  encoding_aes_key: SsZwYFgwmDOfAKIqqQ6GEPjU1ohLVLK2rNcISxYzbOn
  proxy:
    enabled: false
    http: ''
    https: ''
  secret: 81qGwjsand45s-UluYPA16hroksblUVZ6d5w8eVXEkw
  token: zFYzEyQDonVV
share_link_checker:
  enabled: true
  check_interval_hours: 24
